### ISSUE TITLE
Web API image links are broken

### ISSUE THREAD

**Issue by vcellmike** [virtualcell/vcell#1009]
https://vcellapi-beta.cam.uchc.edu:8080/biomodel/256364414/biomodel.vcml - OK

https://vcellapi-beta.cam.uchc.edu:8080/biomodel/256364414/diagram - bad

status = (The server encountered an unexpected condition which prevented it from fulfilling the request), 
request = (GET https://vcellapi-beta.cam.uchc.edu:8080/biomodel/256364414/diagram HTTPS/1.1), 
response = (HTTPS/1.1 - Internal Server Error (500) - 
The server encountered an unexpected condition which prevented it from fulfilling the request)

**Comment by jcschaff** [comment]
fixed by #1010
