### ISSUE TITLE
VCell CLI uses GUI components preventing it being used in BioSimulators' Biosimulators microservice through Singularity.

### ISSUE THREAD

**Issue by CodeByDrescher** [virtualcell/vcell#1045]

**Comment by jcschaff** [comment]
@CodeByDrescher my recommendation for this task is to install minimal graphics support into the docker container to allow diagram rendering (which needs an offscreen Java graphics context).  I know that we are not the only ones who need offscreen java graphics contexts in Docker).

**Comment by CodeByDrescher** [comment]
Fixed problem by telling java to use headless mode whenever booting into CLI. See issue #1007 .
