### ISSUE TITLE
Microscopy Protocols in alpha fails for membrane species

### ISSUE THREAD

**Issue by ACowan0105** [virtualcell/vcell#1114]
Gaussian convolution protocol in alpha currently fails for membrane species, with error "solver stopped unexpectedly". 
 - Test BioModel was created: "Test Gaussian Projection" user ACowan shared with schaff and VCellSupport. 4 Applications - spherical membrane or linear membrane in x, y or z planes.
 - The protocol has not worked for a long time in release (and still not not work).
 - Late in 2023 the convolution was improperly calculated in alpha but gave a result - looked more like a volume species than a membrane species.
 - Subsequently in late 2023 it was fixed and correctly calculated.  Sims in Test Gaussian  Projection with membrane in a single plain all look correct (results are still available)
 - Two days ago was used in another Biomodel, results took a very long time to come back, and convolution function was incorrect (Spherical membrane convolves to a "blob" with value highest in center).  See Biomodel "Bacillus Spore Membrane New FRAP Analysis" user ACowan Application Application "half bleach plus convolved" Sim: "8-23 fit bleach Halfbleach_01_1_2".  
 - Above simulation copied and rerun today (1-23-2-24) now fails "Simulation 'Copy of 8-23 fit bleach Halfbleach_01_1_2' failed
solver stopped unexpectedly, Fail found by monitor, slrmJobID=7642707 jobName=V_ALPHA_266871221_0_16 jobState=FAILED.
- Copies and reran sim in Test Gaussian Project Biomodel, new sim now fails with same error message as above.

**Comment by ACowan0105** [comment]
Tested 2.6.2024 and simulations now are complete.  Results seem correct for membrane species in spherical membrane (see sim results for BioModel Test Gaussian Projection Application Spherical Membrane.

**Comment by CodeByDrescher** [comment]
See previous comment
