### ISSUE TITLE
Execution of example simulation has multiple issues

### ISSUE THREAD

**Issue by jonrkarr** [virtualcell/vcell#112]
VCell now runs successfully in runBioSimulations with 5 example simulation runs. All runs terminate successfully. However, the results contain NaN for outputs of failed simulations (Euler with step size too high).

Example:

SED-ML file `simulation.sedml` in [sbml-core/Vilar-PNAS-2002-minimal-circardian-clock.omex](https://github.com/biosimulators/Biosimulators_test_suite/blob/dev/examples/sbml-core/Vilar-PNAS-2002-minimal-circardian-clock.omex)
- Report `report_Euler_default`
- Plot2D `plot2d_Euler_default`

Because the simulation failed, we would prefer to clearly communicate this to the user by labeled that simulation as FAILED. 

Deeper investigation revealed multiple issues:

- [ ] Exit with non-zero exit code so that the HPC interpets this as a failure.
- [ ] Label the overall status in the log as failed
- [ ] Log should be consistent with outputs. It appears the status in the log may not be accurate.
  - [ ] Log indicates that multiple plots succeeded, but only 2 were produced
  - [ ] Same for reports
- [ ] Capture useful information about the failure in the `output` fields of the log. `output` field doesn't currently have instructive information.

**Comment by jonrkarr** [comment]
I'm also going to remove this COMBINE archive from the examples to reduce potential confusion as people would likely assume these are viable simulations.

**Comment by moraru** [comment]
Fixed
