### ISSUE TITLE
Image Import for Create New Geometry fails

### ISSUE THREAD

**Issue by ACowan0105** [virtualcell/vcell#1172]
When creating a new geometry for PDE sims, image fails to load

NullPointerException-Cannot invoke "org.vcell.vcellij.ImageDatasetReader.getImageSizeInfoForceZ(String, java.lang.Integer)" because "imageDatasetReader" is null

**Comment by CodeByDrescher** [comment]
WE CAN USE THIS WITH BSD-2!!! [Link](http://www.openmicroscopy.org/licensing/)
