### ISSUE TITLE
Update Help in 7.5 alpha prior to next release

### ISSUE THREAD

**Issue by ACowan0105** [virtualcell/vcell#1225]
Need to go through current state of alpha for release and ensure Help is fully updated according to the current Help schema.

**Comment by jcschaff** [comment]
### Content
- custom markdown lives in vcell repo (automatically builds vanilla HTML for in-app and web)
- needs some updating (last content update ACowan 2022-04-22)
### Web
- https://vcell.org/webstart/VCell_Tutorials/VCell_Help/index.html
- poorly formatted
- not readily searchable
- content - last published 2017-08-17
### In-app
- content - always up to date

**Comment by jcschaff** [comment]
will update web vcell help.

**Comment by jcschaff** [comment]
the HTML web help (same as VCell Desktop Help) [vcell.org/webstart/VCell_Tutorials/VCell_Help](https://vcell.org/webstart/VCell_Tutorials/VCell_Help/index.html) is now updated upon every software deployment.

The index.html is now better organized, and the help content parsing and java/web help generation are now decoupled, allowing for future customization of web-only help material (e.g. clone JavaHelpHtmlWriter)

**Comment by jcschaff** [comment]
@ACowan0105 feel free to update content - the content will be deployed to both the Desktop app and the vcell.org website upon each software deployment.

**Comment by CodeByDrescher** [comment]
See #186
