### ISSUE TITLE
Refine the Auth0 login process

### ISSUE THREAD

**Issue by AvocadoMoon** [virtualcell/vcell#1231]
The new authentication method has been implemented within the Java client application, but it's rough around the edges. 

- [x] Remove legacy login GUI and place it within the Web (need it on the web anyways, so why not only on the web)
- [x] There is no formal flow and GUI if you've forgotten your old VCell password
   - [x] Bring over lost password endpoint to the new API
- [ ] The legacy authentication code that is dead is still within the code base
- [x] Browser tabs that open but never close when performing authentication
- [x] Opt out of login (currently seems like you need to login to utilize VCell. There is an offline mode available)
    - [x] Don't want to surprise them with a browser, give some GUI that tells them 
- [x] New users
     - [x] Prompted with webapp to create VCell user
     - [x] Automatically create VCell user from email
- [x] Social Login
- [ ] Authentication and refresh token stored in JSON locally
    - [ ] There's plenty of pro's and con's with this security, clients aren't fully trusted

**Comment by jcschaff** [comment]
@AvocadoMoon can we close this one?
