### ISSUE TITLE
File Open Menu should not include Open Geometry option

### ISSUE THREAD

**Issue by ACowan0105** [virtualcell/vcell#1285]
We no longer store geometries outside of a particular biomodel, so this menu item simply brings up a statement to that effect.  Should just completely get rid of the menu item.

**Comment by ACowan0105** [comment]
The File>Save As Menu also needs to have geometry removed from the options.

**Comment by CodeByDrescher** [comment]
@ACowan0105 I can't find the `File>Save As` menu path, but I did find the `New>Geometry` option. And I removed the `File>Open...` option as well (see attached branch).
