### ISSUE TITLE
Authentication times out quite fast

### ISSUE THREAD

**Issue by danv61** [virtualcell/vcell#1288]
During the vcell launch process, at times the authentication panel (from auth0 in the browser) is asking for auth0 credentials, both email and password.  The Auth0 login window remembered Dan's email, Dan uses email/password credentials for Auth0.

1. A long time passed (> 2 minutes at least)
2. the auth0 password associated with the email was entered into the Auth0 login window in the browser.
3. the browser redirects to localhost and fails with a message 
    `This site can’t be reached 
      localhost refused to connect.
      Try:
         Checking the connection
         Checking the proxy and the firewall
         ERR_CONNECTION_REFUSED
   `

**Comment by jcschaff** [comment]
thanks Dan, please demo the problem for me, I cannot reproduce it using my account - it connect immediately.

**Comment by jcschaff** [comment]
1. clear cookies
2. launch vcell_alpha
3. don't log in for > 120 seconds
4. then browser redirects to http://localhost:51111/oidc_test_callback?code=PrtjP48z7RqnSRYpImMq8YUbY6sgSf0VS3MvgzU7QnSCH&state=o-kKZ4ig6SzgVRvx8FBNeT09CO8LmZQz0O3OiXEJD8A which displays 
`This site can’t be reachedlocalhost refused to connect.
Try:

Checking the connection
[Checking the proxy and the firewall](chrome-error://chromewebdata/#buttons)
ERR_CONNECTION_REFUSED`

**Comment by AvocadoMoon** [comment]
I can fix this problem tomorrow, adding an extended window for users to input their passwords and a proper response for when the window passes instead of continuing with the flow.
