### ISSUE TITLE
Logs of simulation results aren't generated

### ISSUE THREAD

**Issue by jonrkarr** [virtualcell/vcell#130]
This was identified by @bilalshaikh42. We're going to temporarily disable VCell in runBioSimulations until this is fixed.

Below is an excerpt of an error. The full error can be seen at https://run.biosimulations.dev/simulations/61e7431ef9a961c259123a56#tab=log.

```
TempPath Created: /tmp/vcell_temp_37a7b567-b134-424a-834e-b67565b264e97501005096685382529
Python 3.8.10
utilPath: /usr/local/app/vcell/installDir/python/vcell_cli_utils
cliUtilPath: /usr/local/app/vcell/installDir/python/vcell_cli_utils/vcell_cli_utils
cliPath: /usr/local/app/vcell/installDir/python/vcell_cli_utils/vcell_cli_utils/cli.py
statusPath: /usr/local/app/vcell/installDir/python/vcell_cli_utils/vcell_cli_utils/status.py
Traceback (most recent call last):
  File "/usr/local/app/vcell/installDir/python/vcell_cli_utils/vcell_cli_utils/status.py", line 263, in 
    fire.Fire({
  File "/usr/local/lib/python3.8/dist-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/usr/local/lib/python3.8/dist-packages/fire/core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/usr/local/lib/python3.8/dist-packages/fire/core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/usr/local/app/vcell/installDir/python/vcell_cli_utils/vcell_cli_utils/status.py", line 95, in status_yml
    with open(status_yaml_path, 'w' , encoding="utf-8") as sy:
FileNotFoundError: [Errno 2] No such file or directory: '/root/outputs/log.yml'
Failed generating status YAML
SED-ML version level not supported, import may fail
SED-ML version level not supported, import may fail
Unsupported version, import may fail
Found 1 SED-ML document(s) with 1 model(s), 1 simulation(s), 1 task(s), 1  report(s),  1 plot2D(s), and 0 plot3D(s)
```

**Comment by bilalshaikh42** [comment]
@moraru @danv61 
This issue has reoccured in Vell 7.4.0.34

**Comment by danv61** [comment]
Has the validation code been changed recently?
We do not write the log.yml file at '/root/outputs/log.yml'.

**Comment by jonrkarr** [comment]
The validation has not been changed recently.

runBioSimulations expects the log to be stored in `log.yml` relative to the path to the output directory passed to the simulation tool. runBioSimulations manages the location of this output directory.

**Comment by moraru** [comment]
VCell did not change either.  There seems to be a difference in how the locations are bound when the container is deployed by the validation test suite (where the log file is being properly generated) and the runbiosimulations suite (where the log file fails to be generated because vcell can't find the specified location)

**Comment by jonrkarr** [comment]
VCell is being run like this in runBioSimulations:
```bash
singaularity run \
   --bind /home/FCAM/crbmapi/nfs/biosimulations/dev/simulations/61e7431ef9a961c259123a56:/root \
   docker://ghcr.io/biosimulators/vcell:7.4.0.26 \
       -i '/root/input.omex' \
       -o '/root/outputs'
```

It sounds like VCell may be saving the log to a fixed location, rather than to a path relative to the specified output directory (in this example `/root/outputs`, meaning the log is expected to be stored to `/root/outputs/log.yml`).

**Comment by moraru** [comment]
If you look at the error thrown by VCell above that is exactly where it tries write the log file.  Could it be a permission error?  Perhaps vcell is run as docker container by the validation test suite (where it succeeds to write at the proper location) while it is run as singularity container in runbiosimulations?  What else is different between the test environment and the deployed environment?

**Comment by jonrkarr** [comment]
One difference is that the test suite asks results to be saved to a different location. runBioSimulations does not create this output directory (although we could). Is VCell trying to write to a directory that doesn't yet exist?

VCell is provided the same permissions as all other simulation tools.

The test suite primarily uses the Docker image, but also runs a test on the Singularity version of the image.

**Comment by moraru** [comment]
OK, there's the problem. VCell assumes the output directory that was passed in as an argument exists.  We can assert and try to create it if it doesn't.

**Comment by moraru** [comment]
> OK, there's the problem. VCell assumes the output directory that was passed in as an argument exists. We can assert and try to create it if it doesn't.

That's actually not true.  We do assert and create it, including any necessary parents. /root/outputs gets created at the beginning and Java and the solvers operate properly in it.  However the python code to create the initial log file fails for unknow reason.  This is the line that fails:

https://github.com/virtualcell/vcell/blob/6eacc577b77e4d879558a1222253ee5508043032/vcell-cli-utils/vcell_cli_utils/status.py#L99

@jonrkarr @bilalshaikh42 this succeeds in the validation environment but not in the runbiosimulation environments; there must be some security context or something else different

**Comment by jonrkarr** [comment]
One way to debug this is to submit a similar job the UConn HPC where you can try changing the permissions to folders.

This particular job was `/home/FCAM/crbmapi/nfs/biosimulations/dev/simulations/61e7431ef9a961c259123a56/job.sbatch`. Below are the key parts of the job.

```
#!/bin/bash
#SBATCH --job-name=Simulation-run-61e7431ef9a961c259123a56
#SBATCH --chdir=/home/FCAM/crbmapi/nfs/biosimulations/dev/simulations/61e7431ef9a961c259123a56
#SBATCH --output=/home/FCAM/crbmapi/nfs/biosimulations/dev/simulations/61e7431ef9a961c259123a56/job.output
#SBATCH --error=/home/FCAM/crbmapi/nfs/biosimulations/dev/simulations/61e7431ef9a961c259123a56/job.output
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=1
#SBATCH --mem=8000M
#SBATCH --time=20:00
#SBATCH --constraint=simulations&SSE42
#SBATCH --partition=global
#SBATCH --qos=simulations

# configure error handling
set -e

echo -e ''
echo -e '\033[0;36m================================================ Loading Singularity ================================================\033[0m'
export MODULEPATH=/isg/shared/modulefiles
source /usr/share/Modules/init/bash
export PATH=/usr/local/bin:/usr/bin
module load singularity/3.9.2
export SINGULARITY_CACHEDIR=/home/FCAM/crbmapi/singularity/cache/
export SINGULARITY_PULLFOLDER=/home/FCAM/crbmapi/singularity/images/

echo -e ''
echo -e '\033[0;36m============================================ Downloading COMBINE archive ============================================\033[0m'
(ulimit -f 1048576; srun --job-name=Download-project curl -L -o 'input.omex' https://api.biosimulations.dev/runs/61e7431ef9a961c259123a56/download)

echo -e ''
echo -e '\033[0;36m============================================= Executing COMBINE archive =============================================\033[0m'
srun --job-name=Execute-project   singularity run     --tmpdir /local     --bind /home/FCAM/crbmapi/nfs/biosimulations/dev/simulations/61e7431ef9a961c259123a56:/root     --env HPC=1,CPUS=1,GRB_TOKENSERVER=gurobi.cam.uchc.edu     docker://ghcr.io/biosimulators/vcell:7.4.0.26       -i '/root/input.omex'       -o '/root/outputs'
```

**Comment by moraru** [comment]
Thanks, replicating the job manually will make troubleshooting easier.  Overall, it still is bizarre - it is a vanilla file create python call that fails, which works normally in local, debug, or the validation pipeline.

**Comment by jonrkarr** [comment]
There seems to have been a temporary outage. The input file should already be downloaded to the directory for the job `/home/FCAM/crbmapi/nfs/biosimulations/dev/simulations/61e7431ef9a961c259123a56/`.

Bilal set up a status monitor here:
https://status.biosimulations.org/
https://github.com/biosimulations/status

Its pretty good, but not perfect.

**Comment by bilalshaikh42** [comment]
> I'm currently getting a different error when attemptiong to download the input.omex file:
> 
> ```
> 14:44:11 ~/biosim $ cat input.omex 
> <html>
> <head><title>503 Service Temporarily Unavailable</title></head>
> <body>
> <center><h1>503 Service Temporarily Unavailable</h1></center>
> <hr><center>nginx</center>
> </body>
> </html>
> ```

Sorry about that! Everything should be back up and working now

**Comment by bilalshaikh42** [comment]
Yup https://run.biosimulations.dev/simulations/62059a1d986068de026ccfbe#tab=log.

The following curl command can quickly run the test case
```bash
curl -X 'POST' \
  'https://api.biosimulations.dev/runs' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
  "name": "Vcell Test",
  "simulator": "vcell",
  "simulatorVersion": "7.4.0.26",
  "cpus": 1,
  "memory": 8,
  "maxTime": 20,
  "envVars": [],
  "purpose": "other",
  "email": "info@biosimulations.org",
  "url": "https://api.biosimulations.dev/runs/61e7431ef9a961c259123a56/download"
}'
```

**Comment by mpw6** [comment]
I think I found the problem. VCell does create the outputs directory, but not early enough in the process. I reran manually with and without the outputs directory. Without, it does get created, but also gives errors about not being found. If run after manually creating outputs directory, there are no errors.

**Comment by moraru** [comment]
Well, this is UGLY!  @mpw6 is right, but it should not happen that way, it is a Java bug, or perhaps a "not well documented feature", if one wants to be polite.

This line:
https://github.com/virtualcell/vcell/blob/8371c989a3ada2c6ffe6a4359e0657b135ad1704/vcell-cli/src/main/java/org/vcell/cli/CLIStandalone.java#L135
is called before this line:
https://github.com/virtualcell/vcell/blob/8371c989a3ada2c6ffe6a4359e0657b135ad1704/vcell-cli/src/main/java/org/vcell/cli/CLIStandalone.java#L136
(which starts the whole processing)

but it turns out that the Java class method used by the former is:
    public static Path createDirectory(Path dir, FileAttribute<?>... attrs)
        throws IOException
    {
        provider(dir).createDirectory(dir, attrs);
        return dir;
    }
which uses a new java.nio package for FileSystemProvider that has the native implementations asynchronous
