### ISSUE TITLE
Imagej-helper plugin missing

### ISSUE THREAD

**Issue by vcellmike** [virtualcell/vcell#141]
When starting a new Fiji service (Tools -> Start Fiji (ImageJ) service, going through "Install New Plugin" and selecting Plugins Folder -> Open gives an error:
http://vcell.org/webstart/vcell-imagej-helper-Rel_Version_7_4_0_build_34.jar - on Rel
http://vcell.org/webstart/vcell-imagej-helper-Alpha_Version_7_4_0_build_41.jar  - on Alpha

It looks that VCell requires a plugin with identical build number to VCell version. Meanwhile, neither of these jars exist in http://vcell.org/webstart/. 

The error on Mac appears even if I have vcell-imagej-helper-Rel_Version_7_4_0_build_00.jar in Fiji plugins folder, or if I rename it by changing built number.

**Comment by lesloew** [comment]
ImageJ tool does not do anything. the theory is that it is looking for a new version number of imageJ helper that doesn't exist.

**Comment by ACowan0105** [comment]
This is still an issue, needs to be fixed before release

**Comment by vcellmike** [comment]
I manually can build the proper plugins for Rel and Alpha and place them in /webstart and ImageJ plugins folder. Change in Help is necessary.

**Comment by lesloew** [comment]
almost done, just need to update help @vcellmike @ACowan0105

**Comment by vcellmike** [comment]
Need testing and proper plugin GUI
