### ISSUE TITLE
VCell support is not contacted from error message in VCell

### ISSUE THREAD

**Issue by ACowan0105** [virtualcell/vcell#149]
Error message has button to send info to "Let VCell Know"

**Comment by lesloew** [comment]
A good way to generate this is to try to cut and paste a reaction from one model to another

**Comment by moraru** [comment]
the mail capabilities have been fixed (see issue #199 and PR #511)

**Comment by moraru** [comment]
need to check that the error message uses the contact us mail api

**Comment by ACowan0105** [comment]
Dan tested from UCHC and works correctly
