### ISSUE TITLE
Issue with login/ password reset

### ISSUE THREAD

**Issue by ACowan0105** [virtualcell/vcell#155]
Accidently hit reset password reset, get error message that addresses are not valid .  Old password does not work, and cannot reset so completely locked out.
Need to determine who will deal with these issues
Need to send email when account created or when it has been changed.
Need to confirm email address before sending new password/allowing reset.

**Comment by ACowan0105** [comment]
Will modernize methods used for user authentication

**Comment by jcschaff** [comment]
defer until keycloak integration.

**Comment by jcschaff** [comment]
new magic-token based email for recovering access to VCell accounts no longer resets password, the new recover account functionality works well and this problem can no longer happen - Fixed.
