### ISSUE TITLE
Brown et al 2011 model cannot be opened in alpha, can be opened rel.  

### ISSUE THREAD

**Issue by ACowan0105** [virtualcell/vcell#156]
seems to be issue with unit handling

**Comment by moraru** [comment]
There are 6 different Brown et al 2011 published models, only one exhibits the bug:
["Brown et al 2011 Purkinje Biochem-Electrophysiol SCA"](https://vcellapi.cam.uchc.edu/biomodel/98150237)
Model has some parameter with custom unit as a scalar of zero and generates divide by zero for scaling conversion factors

**Comment by moraru** [comment]
Fixed in 70140d528c7a5712a28a8531b9a46e0e81b5217a
