### ISSUE TITLE
Improve ImageJ service and use from VCell

### ISSUE THREAD

**Issue by ACowan0105** [virtualcell/vcell#170]

**Comment by vcellmike** [comment]
1. Update interface for Help and Groovy
2. Create Help at GitHub, VCell website, Help->Help. Describe loading/updating from ImageJ site.
3. Test from MacOS with different security levels, Windows, Linix.

**Comment by jcschaff** [comment]
this issue is regarding the previous implementation of the ImageJ/VCell integration.  closing this issue, there is an epic in ZenHub regarding the new ImageJ/VCell implementation.
