### ISSUE TITLE
Math overrides silently eliminated if param renamed

### ISSUE THREAD

**Issue by ACowan0105** [virtualcell/vcell#177]
Identified as Namescope issue

**Comment by ACowan0105** [comment]
create error on save if overrides inconsistent

**Comment by jcschaff** [comment]
@moraru and @jcschaff discussed this issue and are available for explanation.  

### Background - there are two separate name-spaces for symbols ... biological and mathematical

- A **BioModel** has **named quantities (e.g. parameters, species)** that the user controls and renames when desired.
- A **MathDescription** is the mathematical description underlying all Simulations in the same Application and has **named quantities (e.g. constants, variables)**
- A **MathDescription** is generated automatically from a BioModel Application (the exact form and naming of terms is somewhat VCell version specific).
- A **MathSymbolMapping** captures the mapping of biological terms to the corresponding mathematical terms, but we do not store MathSymbolMappings persistently (too bad !!!). ... The math names and biological names are often not the same.
- A **MathOverride** is a list of mathematical constants which should be overridden to different numerical values ... These name/value pairs are stored where the names are of the mathematical terms not the biological names.

### The problem

- Stored MathOverrides in a BioModel refer to the names of mathematical terms at the time the BioModel was stored (given the version of VCell at the time).  
- Reloading a BioModel with MathOverrides in a different version of VCell can cause some of these overridden parameters to no longer correspond to the newly generated MathDescription terms.
- Interactive use of VCell UI gives some warning (but not sufficient strong warning) when MathOverrides are no longer valid.  It does allow a user to unknowingly re-save the BioModel and discard any invalid MathOverrides.
- Non-interactive use of VCell - in testing frameworks, give no indication that anything is wrong and re-runs the models anyway (throwing away any invalid MathOverrides).

### What can we do?

- For interactive use within VCell UI - don't let users save or re-save BioModels if any MathOverrides are invalid - they must edit them or throw them away manually.
- for non-interactive use within testing frameworks - fail the simulations with any invalid MathOverrides.

**Comment by jcschaff** [comment]
@moraru @danv61 @moraru @CodeByDrescher - take a look

### Possible solution

1. make pass at BioModels stored in database (filter for public/published only to start with), download original stored VCML files, regenerate math, and look for math override problems. - collect those VCML files that have math override issues.
2. record VCell Software Version of each model that had problem
3. make a branch for several legacy VCell software versions that may cover the types of math generation from step (2).
- for each branch, make a separate Docker container (with tag associated with the branch) that will only read in VCML, generate math, and write it back out as VCML.
- this won't be as hard as it sounds - we only need it to generate math and read/write VCML - and after doing a couple of branches, doing more will get easier.
- in a separate exercise - we could look into augmenting these containers to re-run simulations (much harder).
4. for each problematic VCML file from step (1), replace each constant expression (floating point number) with a randomly generated number.
5. re-generate math for any two software versions (by invoking the corresponding containers).
6. generate a map of MathDescription **Constants** with the same value (same random number) ... this mapping can be used to correct any discrepency in **MathOverrides**.
7. [optionally] wrap this in a library and a web service which accepts the original VCML and returns the math override renamings.
8. within UI or within scripts, invoke this service/library to repair broken **MathOverrides**

### Estimate

1 week to generate several branches and corresponding containers.

**Comment by jcschaff** [comment]
short term partial solution is to make sure that invalid math overrides are an error #246

**Comment by moraru** [comment]
Initial fix implemented in https://github.com/virtualcell/vcell/pull/282 as follows:
- In GUI the issue tracker labels this as error and prevents saving, running, and exporting (except VCML); user is informed of issue and manual intervention is necessary to proceed
- In CLI execution is aborted and error is being logged

**Comment by moraru** [comment]
@jcschaff @moraru to scope possible automated handling in the future; this should probably be opened as new issue, and current issue closed

**Comment by ACowan0105** [comment]
@jcschaff please open new issue keeping appropriate comments and close current one.

**Comment by jcschaff** [comment]
closing this issue, see #485
