### ISSUE TITLE
Enable quickrun for stochastic hybrid nonspatial solvers

### ISSUE THREAD

**Issue by ACowan0105** [virtualcell/vcell#188]
required dependency library NetCDF

**Comment by jcschaff** [comment]
this issue is related to the multi-platform build issues in the https://github.com/virtualcell/vcell-solver repo.

**Comment by jcschaff** [comment]
see https://github.com/virtualcell/vcell-solvers/issues/25

**Comment by jcschaff** [comment]
duplicate of https://github.com/virtualcell/vcell-solvers/issues/25
