### ISSUE TITLE
Have VCell Added to Apple App Store

### ISSUE THREAD

**Issue by ACowan0105** [virtualcell/vcell#200]
so Mac users can run VCell client without security problems

**Comment by jcschaff** [comment]
don't think this one is worth it for this kind of project.  The answer to evading security is not look like a suspicious software listening on ports and side-loading frameworks and making calls to the shell for external software.

**Comment by jcschaff** [comment]
maybe we should rename this "install VCell without admin privilege"

**Comment by jcschaff** [comment]
wont do this
