### ISSUE TITLE
Evaluate constant expressions for parameters

### ISSUE THREAD

**Issue by ACowan0105** [virtualcell/vcell#202]
Ask Les for clarification?

**Comment by moraru** [comment]
Not sure what this issue is about

**Comment by lesloew** [comment]
A user may define a paprameter as an expression of constants, e.g. Kf = 10/3.5
When this happens, Kf will not appear in the parameter list of a sim and cannot be changed or scanned.

**Comment by jcschaff** [comment]
this has been fixed several months ago as part of the SEDML import/export work because unit conversion factors needed to be accommodated.
