### ISSUE TITLE
Error when event starts at t=0 in CVODE solver

### ISSUE THREAD

**Issue by ACowan0105** [virtualcell/vcell#217]
Already fixed?

**Comment by danv61** [comment]
Added an Error Issue when the condition is detected in the trigger expression.

**Comment by moraru** [comment]
@danv61 please don't close until fix is merged into master and documenting which commit/PR fixes it

**Comment by moraru** [comment]
I assume this is included in https://github.com/virtualcell/vcell/pull/282?

**Comment by danv61** [comment]
this is included in PR #282 
commit 81f4798
