### ISSUE TITLE
Cleanup and backup simulation results

### ISSUE THREAD

**Issue by jcschaff** [virtualcell/vcell#237]

**Comment by jcschaff** [comment]
### Background

- data is not deleted from simulation results (without manually running the ResultSetCrawler) - this should be automated.
- migrating old results to archival storage (glacier ??) currently still use primary/secondary
- clean up previous results, provide a secondary copy as well.
- weka??

### Tasks

1.

**Comment by moraru** [comment]
superseded by #537
