### ISSUE TITLE
disallow saving BioModels or running simulations if invalid math overrides

### ISSUE THREAD

**Issue by jcschaff** [virtualcell/vcell#246]
disallow saving BioModels or running simulations if any simulation in the BioModel has an invalid math override.  This will prevent silently discarding math overrides.

**Comment by jcschaff** [comment]
@danv61 @moraru I have some thoughts on the scope of this.  Please comment/expand on this.

### Background
regenerating math (preceding saving the BioModel or running Simulations) should generate **ERROR** issues from each Simulation with a bad math overrides (see Simulation.gatherIssues()).

Here are some scenarios:

- saving the BioModel will automatically regenerate math on the client-side and saving should be blocked if any ERROR issues.
- before running Simulation locally (with blue button), math gets generated, gather issues and block if simulation has ERRORs.
- before running Simulation remotely (with green button), it may not force a BioModel save if the old broken model was just loaded from the database ... so again, gather issues and block running for remote simulations as well.

**Comment by jcschaff** [comment]
Dan already merged the code, but some additional testing is needed for export and running @danv61

**Comment by danv61** [comment]
Fixed in PR #322 commit 224066e and 532ef94.
Tested for Run (green button), Save and Export (it still allows export to vcml).
