### ISSUE TITLE
Convert VCell-CLI (et. al. related classes) ) to use logger instead of System.out/err

### ISSUE THREAD

**Issue by CodeByDrescher** [virtualcell/vcell#249]
### Background
- Jim has implemented a logger system into the CLI portion of the code, but we still have code in that project using "System.out.println()" and "System.err.println()" calls. 

### Tasks
- Go through the files in the vcell-cli project and convert all calls to the proper logger.info()/.error()/etc calls.

**Comment by jcschaff** [comment]
this is done.
