### ISSUE TITLE
Dockerfile depends on local machine's maven build.

### ISSUE THREAD

**Issue by CodeByDrescher** [virtualcell/vcell#250]
### Background
- When building a docker image, VCell is "installed" by copying over pre-compiled jars built by maven. While convenient, this directly creates differing builds depending on platform / software versions.
- This issue has largely been avoided because the docker image was being used only for biostimulators purposes, and thus would be built in a fresh ubuntu instance through GitHub actions. 

### Solution
- Create a new Dockerfile that utilizes a 2-step style build alongside the existing Dockerfile.

**Comment by jcschaff** [comment]
- I appreciate the motivation, and was a fan of multistage builds for just this purpose.
- But within our GitHub Action based CI/CD environment, the official Docker images are built in the CI environment, and the unit tests with code coverage and style checks run in that same non-docker environment (the GitHub runners).
- Our current approach to CI/CD is pretty common - and probably results in an easier to understand build/test/deploy pipeline.

**Comment by jcschaff** [comment]
let's leave it as maven running in GitHub runners outside of Docker for now.
