### ISSUE TITLE
Running VCell CLI in Debug Mode causes model simulations to fail (!)

### ISSUE THREAD

**Issue by CodeByDrescher** [virtualcell/vcell#256]
### Background
- Vcell CLI incorporates a -d / --debug flag to programmatically adjust logging levels; this flag is a requirement of Biostimulators as well
- The debug flag prints debug message to the terminal when specified; it should have no impact on runtime simulation.
- When adding the -d flag to vcell-cli command line args (to enable debug operation), models consistently fail even if the passed files would succeed otherwise; it is currently unknown why

**Comment by CodeByDrescher** [comment]
Here's the exception consistently caught and reported:

java.lang.NullPointerException
        at org.vcell.cli.run.RunUtils.generateReportsAsCSV(RunUtils.java:299)
        at org.vcell.cli.run.ExecuteImpl.singleExecOmex(ExecuteImpl.java:292)

**Comment by jcschaff** [comment]
@CodeByDrescher how to reproduce this one, maybe I can take this ticket if I can reproduce it.

**Comment by CodeByDrescher** [comment]
See PR #274 for resolution
