### ISSUE TITLE
Local run sim results window is hidden behind main VCell Window in Alpha

### ISSUE THREAD

**Issue by lesloew** [virtualcell/vcell#261]

**Comment by jcschaff** [comment]
Also on Mac, when loading a local SBML or VCML file, the newly created VCell window shows up behind the current window and is completely hidden - I know to move the top window to look for the new one, but others wouldn't know to do that.

**Comment by ACowan0105** [comment]
Testing at meeting shows this currently works, starts out behind but jumps to front.  Frank may have fixed previously.
