### ISSUE TITLE
The ability to write expressions of parameters and variable for flux boundary conditions is broken in alpha. It still works in Rel.

### ISSUE THREAD

**Issue by lesloew** [virtualcell/vcell#262]
Look at the OpenCleft Application in GeomForMatt

**Comment by moraru** [comment]
I can't reproduce it using either alpha 48 (deployed) or alpha 56 (current codebase in my IDE)

**Comment by lesloew** [comment]
***@***.***

**Comment by lesloew** [comment]
I saved and shared a new model that has the behavior: BoundCondTest. Try to insert the parameter kkk

**Comment by lesloew** [comment]
OK, after I completely closed it and reopened it, I was able to enter kkk. Then I tried adding a new parameter jjj and it worked even without saving. But you saw the problem at the Software Meeting, so I’m not crazy.


From: Loew,Leslie M.
Sent: Tuesday, August 16, 2022 3:02 PM
To: 'virtualcell/vcell' ***@***.***>
Subject: RE: [virtualcell/vcell] The ability to write expressions of parameters and variable for flux boundary conditions is broken in alpha. It still works in Rel. (Issue #262)

I saved and shared a new model that has the behavior: BoundCondTest. Try to insert the parameter kkk

**Comment by moraru** [comment]
I still can't reproduce the error.  No matter what I try, it just works, with or without saving, new parameter, whatever.

**Comment by lesloew** [comment]
I can’t reproduce it either. Maybe Alpha was just in a bad state on my pc.
Best,
Les

From: moraru ***@***.***>
Reply-To: virtualcell/vcell ***@***.***>
Date: Thursday, August 18, 2022 at 1:38 AM
To: virtualcell/vcell ***@***.***>
Cc: "Loew,Leslie M." ***@***.***>, Mention ***@***.***>
Subject: Re: [virtualcell/vcell] The ability to write expressions of parameters and variable for flux boundary conditions is broken in alpha. It still works in Rel. (Issue #262)

*** Attention: This is an external email. Use caution responding, opening attachments or clicking on links. ***

I still can't reproduce the error. No matter what I try, it just works, with or without saving, new parameter, whatever.

**Comment by moraru** [comment]
If it ever shows up again on someone's machine we can reopen and investigate
