### ISSUE TITLE
Test Automated Regression Testing Setup

### ISSUE THREAD

**Issue by CodeByDrescher** [virtualcell/vcell#275]
Once everything is put together, we should do an overnight run of the Regression testing setup to find any final bugs that happen because of integration.

**Comment by CodeByDrescher** [comment]
Blocked by issue #294, will resume after it is resolved and milestone "Adherance to Biosimulators CLI Standard" is complete

**Comment by lesloew** [comment]
see #248. Systems appear to be working.
