### ISSUE TITLE
Omex validation failure due to metadata

### ISSUE THREAD

**Issue by moraru** [virtualcell/vcell#284]
Metadata is incorrect or absent, fails validation.

**Comment by moraru** [comment]
Supposed to be fixed in PR#283

**Comment by moraru** [comment]
@danv61 please close after PR merge and verifying on both published and unpublished models

**Comment by danv61** [comment]
Fixed in #02718c5

**Comment by danv61** [comment]
And in #37ae1b3

The biosimulations validator now says: `Your metadata is likely valid!`
