### ISSUE TITLE
Simulation overrides incorrectly or incompletely translated

### ISSUE THREAD

**Issue by moraru** [virtualcell/vcell#287]
Two bugs on export:
- parameter scans were mapped to RepeatedTasks, but incorrect syntax
- overrides that are functions of other parameters (scanned or unscanned) were not being exported at all

**Comment by moraru** [comment]
This was fixed recently - @danv61 please provide corresponding commit(s) or PR and close

**Comment by danv61** [comment]
PR #282 commits 8fb5ba4 and 1431c70
