### ISSUE TITLE
fix overrides when both species and species_init exist for clamped

### ISSUE THREAD

**Issue by jcschaff** [virtualcell/vcell#340]
<img width="1781" alt="image" src="https://user-images.githubusercontent.com/20616724/189178954-454dabec-9648-457b-a6fc-e4cb010673ed.png">

need biomodel which reproduces this problem @moraru please provide biomodel id

**Comment by jcschaff** [comment]
Legacy vcell model transformations and SBML/SEDML export of MathOverrides for "clamped" species.  Legacy vcell models have stored math descriptions and math overrides with two constants representing the same species value (e.g. one for SpeciesContext "S1" and one for SpeciesContextSpec.initialConcentration "S1_init"), and both were independently overridable.

**Comment by CodeByDrescher** [comment]
New math fixes this problem.
