### ISSUE TITLE
Overriding PM_SurfToVol or ER_VolFract needs resolution

### ISSUE THREAD

**Issue by jcschaff** [virtualcell/vcell#357]
Legacy Biomodels with nonspatial applications described compartment sizes using relative quantities (e.g. PM_SurfToVol , ER_VolFract), but more modern version of VCell use absolute sizes (volumes and surface areas) and these absolute sizes are the parameters which can be overridden.

For such a legacy model, a math override of one or more relative sizes (e.g. PM_SurfToVol or ER_VolFract) is not easily reconciled with the newly generated math.

Explain N absolute compartment sizes versus (N-1) relative compartment sizes.

**Comment by ACowan0105** [comment]
Current state (error on save, run or export other than VCML) may be sufficient for 7.5, but needs more investigation to try to automatically resolve.  Will redesignate as 7.6

**Comment by jcschaff** [comment]
reprioritized for 7.5.0

**Comment by jcschaff** [comment]
### Early Analysis of math equivalence (without MathOverrides)

Comparing original math description (using compartment relative sizes) and newly generated math description (using absolute sizes) for Application **"uncaging"** from **biomodel_89712092**.  The model only has relative sizes (volume fractions and surface to volume ratios).

1. **Original generation Old (18-Jul-2014)**

- SurfToVol_NM = 1.0
- SurfToVol_PM = 0.263
- VolFract_Cytosol = 0.8
- VolFract_Nucleus = 0.1

2. **New math generation (26-Oct-2022)**
math uses absolute compartment sizes (sets Size_Cytosol == 1.0) and uses relative sizes to solve for rest of absolute sizes.

- Size_Cytosol = 1.0
- Size_Extraclellular = 0.27777777777658313
- Size_NM = 0.11111111111111004
- Size_Nucleus = 0.11111111111150196
- Size_PM = 0.29222222227462435

3. **reverse-engineering by hand the relationships apparently used by StructureSizeSolver (I checked the results)**

- VolFract_Nucleus = Size_Nucleus / (Size_Cytosol + Size_Nucleus)
- VolFract_Cytosol = (Size_Cytosol + Size_Nucleus) / (Size_Extracellular + Size_Cytosol + Size_Nucleus)
- SurfToVol_NM = Size_NM / Size_Nucleus
- SurfToVol_PM = Size_PM / (Size_Cytosol + Size_Nucleus)

### But ... one of the expressions in the Math still differ by a factor of 50/36 = 1.388...

**Comment by jcschaff** [comment]
### KFlux_PM_Cytosol is different - but equivalent? -- yes (keep looking)
#### old
- KFlux_PM_Cytosol = (SurfToVol_PM / (1.0 - VolFract_Nucleus))
     **assuming:**
- SurfToVol_PM = Size_PM / (Size_Cytosol + Size_Nucleus)
- VolFract_Nucleus = Size_Nucleus / (Size_Cytosol + Size_Nucleus)
     **substitute and simplify:**
- KFlux_PM_Cytosol = ((Size_PM / (Size_Cytosol + Size_Nucleus)) / (1.0 - (Size_Nucleus / (Size_Cytosol + Size_Nucleus))))
- KFlux_PM_Cytosol = ((Size_PM / (Size_Cytosol + Size_Nucleus)) / (((Size_Cytosol + Size_Nucleus)/(Size_Cytosol + Size_Nucleus)) - (Size_Nucleus / (Size_Cytosol + Size_Nucleus))))
- KFlux_PM_Cytosol = ((Size_PM / (Size_Cytosol + Size_Nucleus)) / (((Size_Cytosol / (Size_Cytosol + Size_Nucleus))))
- KFlux_PM_Cytosol = (Size_PM / Size_Cytosol)
#### new
- KFlux_PM_Cytosol = (Size_PM / Size_Cytosol)

**Comment by jcschaff** [comment]
with mass conservation, looking for contribution of **DAG_PM** in function for **PH_GFP_Cyt** comparing factors in old and new math - this checks out also

**old**
- SurfToVol_PM * VolFract_Cytosol / ((1.0 - VolFract_Nucleus) * VolFract_Cytosol)
- SurfToVol_PM / (1.0 - VolFract_Nucleus)
- (Size_PM / (Size_Cytosol + Size_Nucleus)) / (1.0 - (Size_Nucleus / (Size_Cytosol + Size_Nucleus)))
- (Size_PM / (Size_Cytosol + Size_Nucleus)) / (Size_Cytosol / (Size_Cytosol + Size_Nucleus))
- Size_PM) / (Size_Cytosol

**new**
- Size_PM / Size_Cytosol

**Comment by jcschaff** [comment]
- ended up relaxing the Expression equivalence relative tolerance from 1e-10 to 1e-9 ... I think this is acceptable.
- for legacy non-spatial deterministic applications described in terms of VolumeFractions and SurfaceToVolume ratios, we now solve symbolically for the compartment absolute sizes in terms of the relative sizes (because sometimes the relative sizes were overridden).
- added StructureSizeSolverTest which tests round trip math and exercises both the numeric and symbolic algorithms.

**Comment by jcschaff** [comment]
forgot to restore SEDML Export round trip tests which were temporarily disabled during testing for this issue.
