### ISSUE TITLE
Python-side 2dplotting implementation can not handle repeated tasks

### ISSUE THREAD

**Issue by CodeByDrescher** [virtualcell/vcell#358]
### Background
- VCell CLI could not handle repeated tasks until very recently
- The code used to produce 2d plot diagrams was written in python using a combination of libraries.

### Problem
- Seaborn does not like the matrix of data it is passed when repeated tasks occur; it expects a 1d array instead.
- The Python code uses sedml information to collect information, so careful manipulation must be conducted to fix this problem.

**Comment by danv61** [comment]
Fixed by Logan. We may want to polish it a little bit later on, but for now it does generate the proper plots without error.
