### ISSUE TITLE
SEDML export of overrides may add SBML Rules for expressions

### ISSUE THREAD

**Issue by jcschaff** [virtualcell/vcell#364]
For simple overrides as well as repeated tasks, SEDML needs to find a way of mapping an appropriate transformation on the SBML Document to realize the change.  Numeric quantities are often represented differently in SBML than expressions .. making the task of introducing changes in SEDML more difficult.  If the SEDML exporter gives up, then all models will be imported back into VCell separately (not ideal).

During SEDML export - if the original target value is numeric, and the final overridden value is numeric, then we simply instruct SEDML tasks to change the 'value' attribute of the corresponding SBML quantity.

However, mixing numeric and non-numeric expressions (for original SBML export, and SEDML override needs) is more complicated.

**Comment by ACowan0105** [comment]
@jcschaff can we close this?

**Comment by moraru** [comment]
this was addressed by the various fixes in PR #567
