### ISSUE TITLE
Gson support in VCell should be centralized

### ISSUE THREAD

**Issue by CodeByDrescher** [virtualcell/vcell#367]
### Background
- Currently, a variety of type adapters exist to allow different classes to be converted into json by GSON, the google json library vcell uses. 
- To use these adapters, a builder must be locally instantiated and manually assigned an adapter for each class that needs adaption; this does not automatically include children (so for example, every exception that could need to be logged needs an assigned adapter, as gson does not like automatically converting those classes to json).
- Additionally, gson will quietly override previous adapters if a new one is provided, meaning there's a risk of side effects and unintended behavior if gson builders are passed around.

### Solution
- Create a utility for GSon building as a VCell utility (hosted within `VCellUtilityHub`), and route all calls to Gson building to this utility. This will allow not only to reduce the number of calls needed to build a `Gson` object, but also make it easier to those who need to implement new json exporting features across VCell.

**Comment by jcschaff** [comment]
JSON serialization will be standardized as part of the new VCell REST API effort - may or may not use GSon, but we will develop a vcell (DTO) data transfer object library to support the API.
redundant.
