### ISSUE TITLE
VCell has outdated dependencies that need upgrading.

### ISSUE THREAD

**Issue by CodeByDrescher** [virtualcell/vcell#368]
A number of dependencies in our pom files need upgrading to fix vulnerabilities.

**Comment by CodeByDrescher** [comment]
This issues is blocked by VCell needing JDK8. Upgrades to certain dependencies need higher. Additionally, many transient dependencies need resolving.

**Comment by jcschaff** [comment]
re-enabled dependabot recently - merging these PRs will be a good approach to keeping up to date.  Also - VCell is now using Java 17.
