### ISSUE TITLE
Need to upgrade dependencies and refactor

### ISSUE THREAD

**Issue by CodeByDrescher** [virtualcell/vcell#371]
### Background
- There are a number of dependencies we use with vulnerabilities. Although it's not clear how much they affect us, the risk is still present

### Solutions
- Axis v1.4 -> Axis2 v1.82
- jdom v1.1.3 -> jdom2 v2.0.6.1
- org.jboss.netty v3.2.10 Final -> io.netty v4.1.82 Final OR 5.0.0.Alpha2

**Comment by CodeByDrescher** [comment]
More dependency updates are needed, but blocked by #848

**Comment by jcschaff** [comment]
will use dependabot PRs to inform these upgrades.
