### ISSUE TITLE
M1 Mac Build Failure - update build instructions

### ISSUE THREAD

**Issue by ahalev** [virtualcell/vcell#422]
I'm attempting to set up the command line interface to VCell on an M1 Mac (arch64) using the instructions [here](https://github.com/virtualcell/vcell/blob/master/README_BioSim.md) and am running into issues installing dependencies; I am having test errors in running the dependency install.

Specifically, I am unable to load the libraries `vcell/vcell-core/../nativelibs/mac64/libcombinej.jnilib` and `vcell/vcell-core/../nativelibs/mac64/libjhdf5.jnilib`.

Any suggestions would be appreciated. Full error logs are below. Thank you!

```
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.004 s <<< FAILURE! - in cbit.vcell.resource.NativeLibTest
[ERROR] loadEm(cbit.vcell.resource.NativeLibTest)  Time elapsed: 0.004 s  <<< ERROR!
java.lang.UnsatisfiedLinkError: Can't load library: /Users/ahalev/Dropbox/Avishai/gradSchool/year5/vcell/vcell-core/../nativelibs/mac64/libcombinej.jnilib
        at cbit.vcell.resource.NativeLibTest.loadEm(NativeLibTest.java:16)
```

```
[ERROR] Tests run: 2, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 0 s <<< FAILURE! - in cbit.vcell.simdata.DataSetControllerImplTest
[ERROR] testGetDataIdentifiers(cbit.vcell.simdata.DataSetControllerImplTest)  Time elapsed: 0 s  <<< ERROR!
java.lang.UnsatisfiedLinkError: Can't load library: /Users/ahalev/Dropbox/Avishai/gradSchool/year5/vcell/vcell-core/../nativelibs/mac64/libjhdf5.jnilib
        at cbit.vcell.simdata.DataSetControllerImplTest.setUp(DataSetControllerImplTest.java:35)

[ERROR] testDoDataOperation(cbit.vcell.simdata.DataSetControllerImplTest)  Time elapsed: 0 s  <<< ERROR!
java.lang.UnsatisfiedLinkError: Can't load library: /Users/ahalev/Dropbox/Avishai/gradSchool/year5/vcell/vcell-core/../nativelibs/mac64/libjhdf5.jnilib
        at cbit.vcell.simdata.DataSetControllerImplTest.setUp(DataSetControllerImplTest.java:35)

```

**Comment by jcschaff** [comment]
must be verified on M1/M2 box.

**Comment by jcschaff** [comment]
build verified on Macos Ventura 13.4 using updated instructions in [README.md](https://github.com/virtualcell/vcell/blob/master/README.md) referenced in [README_BioSim.md](https://github.com/virtualcell/vcell/blob/master/README_BioSim.md)

**Comment by CodeByDrescher** [comment]
The issues described here are actually still present; CLI still uses the old HDF library, which does NOT support M1 arch. With JHDF now updated to use attributes, we should be able to actually fix this issue.

**Comment by CodeByDrescher** [comment]
Just confirmed, following the instructions, there should not be any more issues using CLI on Arm chips.
