### ISSUE TITLE
Change export default substance unit from nmol to umol

### ISSUE THREAD

**Issue by moraru** [virtualcell/vcell#426]
Poses least problems with scaling when exporting to OMEX/SBML since VCell default of uM translates directly to umol/dm3

**Comment by jcschaff** [comment]
taking this issue - quick fix (but have to test)

**Comment by jcschaff** [comment]
@moraru just a bit more involved ... have to make sure appropriate math override correction templates are in place for transforming math overrides to umol/dm2
