### ISSUE TITLE
Transform to stochastic GUI widget bombs out

### ISSUE THREAD

**Issue by moraru** [virtualcell/vcell#428]
Bug appears when invoking the transform to stochastic capable tool and the user selects more than one compatible reaction to be transformed and clicks OK:
- the transformation bombs out with a "duplicate listener"error
- only the first reaction selected is being transformed
- on subsequent attempts to transform, it gets worse: after a second error generation the panel actually fails to repaint properly

**Comment by ACowan0105** [comment]
This is likely fixed by moving the transform work to a non-swing thread (see #425)

**Comment by moraru** [comment]
Verified as fixed
