### ISSUE TITLE
Python Unification

### ISSUE THREAD

**Issue by CodeByDrescher** [virtualcell/vcell#471]
VCell requires python in a variety of its projects, however there is not only a lack of consistency, but the way the implementations are used at runtime create limitations and bugs that are hard to work around. (Loading and verification of python, dependency on poetry, etc.). 

We should make two important changes to how python-based programs are dealt with in VCell:
- While still keeping with the concept of decoupling, Python should only be managed in one place in VCell; there isn't a good justification for having multiple implementations.
- Minimal runtime installation or loading should occur; this can only be beneficial for security, efficiency, and bugfixing.

Exact implementation still being worked out.

**Comment by jcschaff** [comment]
considerable improvement to the Python libraries has occurred since this issue was created.  Unit tests and Poetry have improved the situation considerably.  The management of Python invocations from Java is now sensible.
