### ISSUE TITLE
Cannot create output Function on a membrane which is a function of cartesion coordinates

### ISSUE THREAD

**Issue by lesloew** [virtualcell/vcell#486]
Tried to create this function: ((((x - 11.0) ^ 2.0) + ((y - 11.0) ^ 2.0)) < (4))*(z<2). When I tried to assign it to a membrane (spherical cell geometry) I get the following error:
Function 'BleachAreaRad2' cannot be added.
	The expression for 'BleachAreaRad2' includes at least one Volume variable. Please make sure that only Membrane variables are referenced in Membrane output functions.

**Comment by danv61** [comment]
Fixed in 087e174
