### ISSUE TITLE
cell kinematics are not exported/imported

### ISSUE THREAD

**Issue by moraru** [virtualcell/vcell#524]
This generates math equivalency failure on roundtrip for simcontexts where velocities are defined.
If they are not supported by SBML spatial, then we should check and flag the simcontext as unsupported.
If they are, then they should be exported/imported.

**Comment by jcschaff** [comment]
@moraru Advection is supported in SBML spatial (I had to look it up to be sure).  I'll look into supporting this.

<img width="694" alt="image" src="https://user-images.githubusercontent.com/20616724/199034518-3b4d24e7-2adb-4b6f-921f-8c66eb7a4163.png">

**Comment by jcschaff** [comment]
Support for advection is already present, passes simple tests.
