### ISSUE TITLE
Math equivalency check trips on vcRegion function definitions

### ISSUE THREAD

**Issue by moraru** [virtualcell/vcell#525]
Throws ExpressionBindingException when formal function definition returns 'vcRegionVolume(LITERAL)' or 'vcRegionArea(LITERAL)'
Example biomodel_111113048

**Comment by jcschaff** [comment]
ExpressionUtils.functionallyEquivalent() couldn't handle user defined functions - now this is supported in a fail-safe way.  simple 'vcRegionVolume(LITERAL)' functions are substituted with corresponding symbols.  For other USERDEFINED functions with arguments (eg. gradient functions, function arguments must match exactly).
If this becomes a problem, we can make it more sophisticated.
