### ISSUE TITLE
Extraneous Z boundary condition present in 2D geometry math

### ISSUE THREAD

**Issue by moraru** [virtualcell/vcell#526]
Original (database version) of math description for some 2D spatial applications contains spurious references to Z dimension (extra constant and PDE equation for Z boundary conditions)
Example biomodel_62533452

This is in fact a bug of legacy math generation.

However, since the Z boundary conditions do not have any effect in this case, the math equivalency test for newly generated math should ignore the spurious legacy elements related to Z in an application with 2D geometry.

**Comment by jcschaff** [comment]
filtered these extra equation terms during math comparison.
