### ISSUE TITLE
Assignment rules not handled properly during round trip

### ISSUE THREAD

**Issue by moraru** [virtualcell/vcell#538]
Export/import of explicit assignment rules for species and global parameters are being skipped. Depending on situation, this may be caught by math equivalency testing or by math overrides checking, or not at all.

Desired behavior:
- on export, make sure that explicit assignment rules present in an application are being parsed and not skipped for all targetable variables (global params, species "init", comp size), and take precedence over default values
- on import, we do not have to reconstitute them as explicit assignment rules (this no need to add VCell-specific annotations during the export phase), but just make sure they end up with the right expression in the proper place (global param definition, species init, comp size)

**Comment by moraru** [comment]
@jcschaff check with @danv61 who discovered this issue and is currently making changes to the same area of code while working to fix the duplicate id issue (#519)

**Comment by danv61** [comment]
Export is fixed now in e603d68

**Comment by danv61** [comment]
Fixed in #617 (commit ce518ed)
