### ISSUE TITLE
Reaction conversion from lumped to distributed fails for most expressions

### ISSUE THREAD

**Issue by moraru** [virtualcell/vcell#542]
If a reaction of general type is in extents of substance/time ("lumped rate") it cannot be converted to extents of concentration/time ("regular rate") unless the rate expression contains an explicit multiplier with the symbol name of the compartment.

To reproduce: create a new biomodel with a single reaction of type general (molecules/s), and type in an arbitrary number (or expression) for the rate.  Click "convert to uM/s" button.

**Comment by jcschaff** [comment]
this may be a feature and was intentional - I think that we should leave such reactions as lumped.  @moraru what are your thoughts.

**Comment by moraru** [comment]
I don't see a reason for this (new) behavior.  It creates a whole set of problems:

**Comment by moraru** [comment]
Intermediate solution is to changed behavior as follows:
- simplification attempt to find scale factor expanded by substituting symbols recursively up to one step short of numeric value
- use a force flag so if called by user from GUI it will explicitly divide by compartment size even if it can't cancel it out

**Comment by CodeByDrescher** [comment]
@moraru will check and close (or divert the rest to 7.6)

**Comment by moraru** [comment]
Fixed as described in comment above
