### ISSUE TITLE
Simulations fail in Alpha Build 80

### ISSUE THREAD

**Issue by lesloew** [virtualcell/vcell#543]
Simsare dispatched and show 0% progress, then here is the error message:
One job from Simulation 'Copy of Copy of Simulation1' failed
solver stopped unexpectedly, Fail found by monitor, slrmJobID=5551262 jobName=V_ALPHA_246610800_0_0 jobState=FAILED

**Comment by moraru** [comment]
Fixed in https://github.com/virtualcell/vcell/releases/tag/7.4.0.82 deployed earlier today.
