### ISSUE TITLE
Math Generation fails when parameter name conflicts with rate math-side variable name

### ISSUE THREAD

**Issue by moraru** [virtualcell/vcell#553]
If the expression of a reaction rate (or lumped rate etc.) uses a local or global parameter in the expression with the same name as the standard math side naming of parameters with predefined roles (e.g. J_r0, Kf_r0) math generation fails with a RuntimeException.

**Comment by jcschaff** [comment]
### TO REPRODUCE
- create simple reaction a->b
- Kf = J_r0 ... local user defined parameter

during math generation there is a conflict - fails.

**Comment by jcschaff** [comment]
### REPODUCE 2
general kinetics
J = J_r0, J_r0 = 3

**Comment by jcschaff** [comment]
### REPRODUCE 3
General Kinetics
J = a + a_r0, a=1, a_r0=2

>>> math complains math constant a_r0=1 conflicts with generated constant a_r0=2

**Comment by jcschaff** [comment]
look into applying TokenMangler.getNextEnumeratedToken() when there is a conflict.

**Comment by jcschaff** [comment]
change Math Generation AbstractMathMapping.getMathSymbol0 policy to always mangle local names even if there is only one.
