### ISSUE TITLE
Converting reaction results in orphaned math overrides

### ISSUE THREAD

**Issue by moraru** [virtualcell/vcell#554]
Changing a reaction extent (e.g. general to lumped) will orphan any math overrides of the reaction rate.

To reproduce: create biomodel with 1 reaction of type general, set rate to arbitrary value, create 1 simulation, edit simulation to override rate value, convert reaction, refresh math.

**Comment by jcschaff** [comment]
Is this one worth fixing - if the user deliberately changes from General Distributed (uM/s) to General Lumped (umol/s) they will see the problem and fix it.

What is the use case for our work (SBML round trip?).  @moraru - I want to recall what the real motivation is.
