### ISSUE TITLE
Duplicate PropertyChangeListener entries generate exceptions

### ISSUE THREAD

**Issue by moraru** [virtualcell/vcell#556]
Cause: not removing old listener before adding new listener if same instance.

**Comment by moraru** [comment]
Bug exposed in Parameter class during validation runs but should be eventually corrected in many places.

**Comment by moraru** [comment]
Fixed in 1a7bbc3218e20c8a3e17b1f94b718fe49e5b413b for Parameter class which leads to roundtrip valiodation failure.

**Comment by moraru** [comment]
Should be fixed more generally in the future.

**Comment by moraru** [comment]
fix deployed in #567

**Comment by jcschaff** [comment]
per above comment, fix deployed in #567.
