### ISSUE TITLE
Not converting lumped to distributed kinetics breaks many things

### ISSUE THREAD

**Issue by moraru** [virtualcell/vcell#615]
While fixing orphan overrides related issues in PR #607 coercing lumped kinetics into distributed kinetics was dropped during import.  This creates several problems:
- (minor) import behavior and variable naming is inconsistent between GUI and CLI
- (major) every single biomodel that has both a compartmental and a spatial application will no longer roundtrip into a single biomodel, since the reactions in the underlying model and reactions are no longer the same
- (major) import and execution will fail for many stochastic models originated from vcell and for most stochastic models originating from other

**Comment by jcschaff** [comment]
The trick is to apply the distributed transformation right after the sedml override application... I think.

**Comment by moraru** [comment]
Because successful application of math overrides can only happen after simcontexts are created, coercing must be done ahead of time (unless the entire sedml processing is being overhauled).

**Comment by moraru** [comment]
coercing while in the import phase will break the fix for resolving constant rate parameters as implemented in #607

**Comment by moraru** [comment]
Fixed by 6de113f6631e7708081fc163a98f5ee2f67f0139 and d4e52b9923ca157b14277073760663a35843e1b0 and be6bc17c502110d7e26b049051a17d4b63ba0901

**Comment by moraru** [comment]
deployed by PR #619
