### ISSUE TITLE
Escape commas in row labels for CSV SED-ML reports

### ISSUE THREAD

**Issue by jonrkarr** [virtualcell/vcell#62]
CSV files produced for SED reports are not properly escaped. This can cause these files to be interpreted incorrectly.

SED data set labels that include commas should be enclosed in double quotes e.g., `"A, B, C"`. 

I believe this is where this should be revised:
https://github.com/virtualcell/vcell/blob/82f9e4313a191fee84d2f167f3f0f9de1ea0e18c/vcell-cli/src/main/java/org/vcell/cli/CLIUtils.java#L162

Here's a snippet of a SED-ML document which can generate this problem.
```xml
<report id="simulation_1" name="simulation 1">
    <listOfDataSets>
        <dataSet id="data_set_PSwe1M" label="Phosphorylated, modified Swe1" dataReference="PSwe1M"/>
    </listOfDataSets>
</report>
```

**Comment by gmarupilla** [comment]
Fixed in this [commit](https://github.com/virtualcell/vcell/commit/d1b2ee8ed9c9a0546892269ad88eb05ac40b05f3)
