### ISSUE TITLE
Errors in CSV to HDF5 conversion are being supressed

### ISSUE THREAD

**Issue by jonrkarr** [virtualcell/vcell#63]
When conversion from CSV to HDF5 fails, VCell neither produces an error message nor exists with an error. This can occur when VCell tries to convert malformed CSV to HDF (see #62) such as with [this COMBINE archive file](https://github.com/biosimulators/Biosimulators_test_suite/blob/dev/examples/sbml-core/Ciliberto-J-Cell-Biol-2003-morphogenesis-checkpoint-continuous.omex).

Either VCell should catch such errors or exit when such errors occur.

I believe the error handling should be implemented here: https://github.com/virtualcell/vcell/blob/82f9e4313a191fee84d2f167f3f0f9de1ea0e18c/vcell-cli/src/main/java/org/vcell/cli/CLIUtils.java#L516

**Comment by gmarupilla** [comment]
[Exceptions](https://github.com/virtualcell/vcell/commit/dcb381f86d90885b4de6820bab22f73d73aad501) for failed executions are now being handled and logged as an error stream.

**Comment by gmarupilla** [comment]
Now, all process builder errors are handled and printed to logs with the printProcessErrors method.

https://github.com/virtualcell/vcell/blob/1df4d3d19990269147999984086ece989c1e6534/vcell-cli/src/main/java/org/vcell/cli/CLIUtils.java#L504
