### ISSUE TITLE
Transform to stochastic erroneous

### ISSUE THREAD

**Issue by moraru** [virtualcell/vcell#632]
Transform to stochastic makes two mistakes:
- incorrectly transforms general reaction rate
- incorrectly labels existing mass action reaction as incompatible with mass action math (!!)

Simple biomodel to illustrate the problem `---0-rxn-test` shared with VCell_support

**Comment by danv61** [comment]
fixed wrong order of reactions in transform mass action panel in commit 1e25f65
unselected / non-editable checkbox for existing mass actions is correct, they don't need to be transformed
