### ISSUE TITLE
Multiple unit definitions without id

### ISSUE THREAD

**Issue by moraru** [virtualcell/vcell#636]
SBML exporter generates one or more unit definitions without an id.  These are various scalars of dimensionless.

This is invalid SBML.

Example below, 3 scalars of dimensionless without Sid:

    <listOfUnitDefinitions>
      <unitDefinition id="Unit_umol">
        <listOfUnits>
          <unit exponent="1" kind="mole" multiplier="1" scale="-6"/>
        </listOfUnits>
      </unitDefinition>
      <unitDefinition id="Unit_l">
        <listOfUnits>
          <unit exponent="1" kind="litre" multiplier="1" scale="0"/>
        </listOfUnits>
      </unitDefinition>
      <unitDefinition id="Unit_dm2">
        <listOfUnits>
          <unit exponent="2" kind="metre" multiplier="1" scale="-1"/>
        </listOfUnits>
      </unitDefinition>
      <unitDefinition id="Unit_dm">
        <listOfUnits>
          <unit exponent="1" kind="metre" multiplier="1" scale="-1"/>
        </listOfUnits>
      </unitDefinition>
      <unitDefinition id="Unit_s">
        <listOfUnits>
          <unit exponent="1" kind="second" multiplier="1" scale="0"/>
        </listOfUnits>
      </unitDefinition>
      <unitDefinition id="Unit_K">
        <listOfUnits>
          <unit exponent="1" kind="kelvin" multiplier="1" scale="0"/>
        </listOfUnits>
      </unitDefinition>
      <unitDefinition>
        <listOfUnits>
          <unit exponent="1" kind="dimensionless" multiplier="1" scale="0"/>
        </listOfUnits>
      </unitDefinition>
      <unitDefinition id="Unit_C_mol_1">
        <listOfUnits>
          <unit exponent="1" kind="coulomb" multiplier="1" scale="0"/>
          <unit exponent="-1" kind="mole" multiplier="1" scale="0"/>
        </listOfUnits>
      </unitDefinition>
      <unitDefinition id="Unit_C_nmol_1">
        <listOfUnits>
          <unit exponent="1" kind="coulomb" multiplier="1" scale="0"/>
          <unit exponent="-1" kind="mole" multiplier="1" scale="-9"/>
        </listOfUnits>
      </unitDefinition>
      <unitDefinition id="Unit_molecules_pmol_1">
        <listOfUnits>
          <unit exponent="1" kind="item" multiplier="1" scale="0"/>
          <unit exponent="-1" kind="mole" multiplier="1" scale="-12"/>
        </listOfUnits>
      </unitDefinition>
      <unitDefinition>
        <listOfUnits>
          <unit exponent="1" kind="dimensionless" multiplier="1000000000" scale="0"/>
        </listOfUnits>
      </unitDefinition>
      <unitDefinition id="Unit_mV_C_K_1_mol_1">
        <listOfUnits>
          <unit exponent="1" kind="volt" multiplier="1" scale="-3"/>
          <unit exponent="1" kind="coulomb" multiplier="1" scale="0"/>
          <unit exponent="-1" kind="kelvin" multiplier="1" scale="0"/>
          <unit exponent="-1" kind="mole" multiplier="1" scale="0"/>
        </listOfUnits>
      </unitDefinition>
      <unitDefinition>
        <listOfUnits>
          <unit exponent="1" kind="dimensionless" multiplier="1" scale="0"/>
        </listOfUnits>
      </unitDefinition>
      <unitDefinition id="Unit_uM_um3_molecules_1">
        <listOfUnits>
          <unit exponent="1" kind="mole" multiplier="1" scale="-6"/>
          <unit exponent="-1" kind="litre" multiplier="1" scale="0"/>
          <unit exponent="3" kind="metre" multiplier="1" scale="-6"/>
          <unit exponent="-1" kind="item" multiplier="1" scale="0"/>
        </listOfUnits>
      </unitDefinition>
      <unitDefinition id="Unit_s_1">
        <listOfUnits>
          <unit exponent="-1" kind="second" multiplier="1" scale="0"/>
        </listOfUnits>
      </unitDefinition>
      <unitDefinition id="Unit_s_1_uM_1">
        <listOfUnits>
          <unit exponent="-1" kind="second" multiplier="1" scale="0"/>
          <unit exponent="-1" kind="mole" multiplier="1" scale="-6"/>
          <unit exponent="1" kind="litre" multiplier="1" scale="0"/>
        </listOfUnits>
      </unitDefinition>
    </listOfUnitDefinitions>

**Comment by jcschaff** [comment]
@moraru I'll look into this.
