### ISSUE TITLE
Append data for SED Plot2D and Plot3d to HDF5 files

### ISSUE THREAD

**Issue by jonrkarr** [virtualcell/vcell#64]
At the end of the HARMONY meeting, Bilal and I had a long meeting with Herbert, Lucian, Frank and some others where we discussed integration of runBioSimulations with BioModels and the visualizations in runBioSimulations.

Basically, Lucian and Frank expected runBioSimulations to, by default, display the plots described in the executed SED-ML file(s). I agree that for a certain set of users, this is a reasonable expectation and this would be convenient for users coming from BioModels. In that case, users could quickly see an interactive version of something similar to BioModels' curators' notes.

To make this possible, each simulation tool needs to save the data for each X and Y data generator of each curve of each Plot2D to HDF5 (same for Plot3D). 

For convenience and simplicity, I thinks reasonable to append this to the same HDF5 output we're using for reports (`reports.h5`). Obviously, the file name is a slight misnomer. We could change that. Because reports and plots have to have unique ids, there's no problem with saving both reports and plots to the same HDF5 file.

One way to implement this is to simply add a SED report for each SED plot2d and plot3d object shortly after SED documents are imported. After this, VCell code can execute this pseudo report and export its data just like any true report.

Todo
- [x] Append data for plots to the HDF5 file with data for reports
  - [x] Collect all of the data generators needed for a plot
  - [x] Create a "pseudo" SED data set for each data generator involved in the plot
  - [x] When this pseudo report is saved to HDF5 or CSV, the exported `id`s and `label`s of these pseudo data generators should be the id of the corresponding data generator
- [x] Temporarily also save the same data for plots to CSV because runBioSimulations is still working with CSV. (We can change this once VCell is settled on HDF5.)

**Comment by gmarupilla** [comment]
Being handled by creating in memory SED-ML object for Plots only archive by following a temp convention using Python  CLI util package. 

https://github.com/virtualcell/vcell/blob/1df4d3d19990269147999984086ece989c1e6534/vcell-cli/src/main/java/org/vcell/cli/CLIUtils.java#L552
