### ISSUE TITLE
Add additional metadata to HDF5 files

### ISSUE THREAD

**Issue by jonrkarr** [virtualcell/vcell#65]
One of the reasons we've decided to used HDF5 instead of CSV is to support metadata. The initial metadata was
- `dataSetIds`: `string[]`: list of ids of data sets in order of the data sets (rows) of the HDF5 data set.
- `dataSetLabels`: `string[]`: list of labels of data sets
- `dataSetDataTypes`: `string[]`: list of types of the data sets (e.g., integer, boolean, float)
- `dataSetShapes`: `integer[][]`: list of tuples of the shape of each data set

I'd like to add a little more metadata:
- `_type`: `string`: type of the data set (`SedReport`, `SedPlot2D`, or `SedPlot3d`)
- `id`: `string`: id of the report
- `name`: `string` | undefined: name of the report  -- this attribute can be left out of a report doesn't have an id
- `dataSetNames`: `(string | null)[]`: names of the data sets

The formerly is related to making is possible for runBioSimulations to display plots described in SED documents. For this to be possible, we need to save the data for plots to HDF5 files similar to what we've doing for reports. See #64.

**Comment by gmarupilla** [comment]
Achieved using [biosimulators-utils](https://pypi.org/project/biosimulators-utils) PYPI package
