### ISSUE TITLE
Multiple spatial validation errors

### ISSUE THREAD

**Issue by moraru** [virtualcell/vcell#653]
Example biomodel_13737035.

Error[ Line 41] Column 54: (SBML Validation Rule #10102) An SBML XML document must not contain undefined elements or attributes in the SBML namespace. Documents containing unknown elements or attributes placed in the SBML namespace do not conform to the SBML specification. Reference: L3V2 Section 4.1 Element 'domain' is not part of the definition of 'domain' in SBML Level 3 Version 2 Package spatial Version 1.

above refers to this:

        <spatial:domain spatial:domainType="cytosol_extracellular_membrane" spatial:id="membrane_extracellular0_cytosol1">
          <spatial:other/>
        </spatial:domain>

fiixing that generates this:

Error[ Line 255] Column 103: (SBML Validation Rule #spatial-21350) The attribute 'spatial:unitSize' on a <compartmentMapping> must have a value between 0 and 1, inclusive. Reference: L3V1 Spatial V1 Section A CompartmentMapping with id 'cytosolerMembrane' has a unitSize of 57600.

and this:

RuntimeException-Error adding model to SEDML document : SimContext 'SS check' could not be exported to SBML :Failed to translate SBML model into BioModel: Unable to create VC structureMappings from SBML compartment mappings : The value for property unitSize is not defined in compartmentMapping for Level 3 and Version 2.

**Comment by jcschaff** [comment]
@moraru I have a stale discussion with Lucian and Frank about the unitSIze issue.  [this error is now a warning, and only if the unitSize is nondimensional](https://github.com/sbmlteam/libsbml/pull/276)
