### ISSUE TITLE
math compare fails due to different number of fast invariants

### ISSUE THREAD

**Issue by moraru** [virtualcell/vcell#684]
Legacy math always generates fast systems with same number of fast rates and fast invariants. New math generates more invariants then rates, probably due to not using mass conservation when deriving the fast system.

This results in compare failure even if actually equivalent.

**Comment by jcschaff** [comment]
applications with this problem (more fast invariants in new math than in old)

biomodel_12522025.vcml:purkinje9
biomodel_12522025.vcml:purkinje9-ss
biomodel_12522025_spatial.vcml:purkinje9
biomodel_17257105.vcml:spatial
biomodel_17326658.vcml:Mg Green - 500 uM
biomodel_22403244.vcml:spatial
biomodel_22403576.vcml:Spatial
biomodel_28625786.vcml:simple_3
biomodel_28625786.vcml:Fig4_neuro2
biomodel_28625786.vcml:Fig1-2 neuro1
...
biomodel_2917999.vcml:Figure 5.8
biomodel_9254662.vcml:FastBuffExpReceptor

**Comment by jcschaff** [comment]
The purpose of the fast invariants are to reduce enough degrees of freedom to make the system of fast rates solvable.

## Model hernjak: purkinje_2D model (biomodel_12522025.vcml)
In the case of this model, there are two fast reactions.  
1. Reaction `BufferBound`: Endogenous Calcium Buffering in the Cytosol `(Buffer + Ca -> BufferB)`
2. Reaction `Fura2Bound`: Calcium Buffering by the flourescent indicator in the Cytosol `(Fura2 + Ca -> Fura2B)`

### Original MathDescription
```
	FastSystem {
		FastInvariant	( - Fura2 + Ca - Buffer);
		FastInvariant	(Fura2B + Fura2);
		FastRate	 - J_BufferBound;
		FastRate	 - J_Fura2Bound;
	}
```
there is a fast rate for each of `BufferBound` and `Fura2Bound` reactions (2 equations), and there are 5 unknowns in the fast rates (Ca, Buffer, BufferB, Fura2, Fura2B).

to add 3 more equations:
fast invariant: `(- Fura2 + Ca - Buffer)`
fast invariant: `(Fura2B + Fura2)`
and an implied fast invariant from a zero-rate differential equation for Buffer:  d/dt(Buffer) = 0 ==> `(Buffer)`

      **Now there are 5 equations in terms of 5 unknowns - the system is solvable - Good!**

### Newly Generated MathDescription
(for clarity, I cancelled unit factors which don't change the math)
```
	FastSystem {
		FastInvariant	(Ca_cytosol - Buffer_cytosol - Fura2_cytosol);
		FastInvariant	IP3_cytosol;
		FastInvariant	(Fura2B_cytosol + Fura2_cytosol);
		FastInvariant	h_ERM;
		FastRate	 - J_BufferBound;
		FastRate	 - J_Fura2Bound;
	}
```
same two fast reactions (but renamed to species context names) 
1. Reaction `BufferBound`: Endogenous Calcium Buffering in the Cytosol `(Buffer_cytosol + Ca_cytosol -> BufferB_cytosol)`
2. Reaction `Fura2Bound`: Calcium Buffering by the flourescent indicator in the Cytosol `(Fura2_cytosol + Ca_cytosol -> Fura2B_cytosol)`

there is a fast rate for each of `BufferBound` and `Fura2Bound` reactions (2 equations), and there are 5 unknowns in the fast rates (Ca_cytosol, Buffer_cytosol, BufferB_cytosol, Fura2_cytosol, Fura2B_cytosol).

to add 3 more equations:
fast invariant: `(- Fura2_cytosol + Ca_cytosol - Buffer_cytosol)`
fast invariant: `(Fura2B_cytosol + Fura2_cytosol)`
and an implied fast invariant from a zero-rate differential equation for Buffer_cytosol:  d/dt(Buffer_cytosol) = 0 ==> `(Buffer_cytosol)`

#### and two additional harmless fast invariants (which introduces and constraints two more variables - IP3 and h_ERM)
fast invariant (h_ERM)
fast invariant (IP3_cytosol)

      **Now the fast system has 7 equations in terms of 7 unknowns - the system is solvable - Good! (but the fast invariants for h_ERM and IP3_cytosol are not needed).**

**Comment by jcschaff** [comment]
When comparing for math equivalence of fast systems, here is a PITA stragegy which should always work (only try it if the number of expressions don't match)

1. take the N fast invariants and solve for N of the VolVariables (symbolically).
2. substitute the N solved VolVariables into the M fast rates (there should be M fast rates and M remaining unknowns)
3. compare the expressions for the substituted fast rates and ignore the fast invariants.

**Comment by jcschaff** [comment]
@moraru what do you think, there may be a simpler solution, but here is my initial analysis.

**Comment by jcschaff** [comment]
I'll do the work, but we should discuss it.

**Comment by jcschaff** [comment]
Note: the fast invariants are conceptually very similar to the mass conservation relationships for the regular math generation, however the fast invariants are not in solved form (they are implicitly defined ... g(x)=0).  These fast invariant expressions together form a linear system of the form Ax=0 (where x are VolVariables, and A is function of constants).  Generally, A is not full rank (otherwise you wouldn't need the fast rates to solve for the variables).

For regular Functions derived from mass conservation relationships in the MathDescription, they are already in solved form so substitution is directly applied - here we have to first solve symbolically before substitution for some x's (VolVariables) in terms of the others (VolVariables and Constants) ... and then do a deep substitution of the solved functions back into the fast rates. 

After substitution, we should be left with M fast rates in terms of M variables - and we can compare the M fast rate expressions for equivalence (who cares about the fast invariants!!!)

**Comment by moraru** [comment]
This means skip checking the invariants since they cannot easily and reliably quick-fail non-equivalent maths. Always full comparison if fast reactions are involved seems the right approach.

**Comment by jcschaff** [comment]
I finallyt introduced a very simple fix (a bit of cheating) which makes fast invariant compare problems go away during equivalence testing.

We now ignore equivalence of trivial fast invariants (ones with only one symbol - these were the extra fast invariants which were sometimes added without need).

Legacy math generation equivalence testing now passes 21 more applications.
