### ISSUE TITLE
Add metadata to HDF5 files to support the data service that Bilal is building

### ISSUE THREAD

**Issue by jonrkarr** [virtualcell/vcell#70]
@bilalshaikh42 wants to introduce a little more metadata into HDF5 files to make it easier to use the HDF5 data service. I think this will also also help users understand how data is mapped into HDF5 files.

This metadata needs to be introduce here:
https://github.com/virtualcell/vcell/blob/3a9904f9c6a03408821c2d0a6e4d4e7fbb1cc384/vcell-client/src/main/java/cbit/plot/gui/Plot2DDataPanel.java#L500

Below are the changes the need to be made. There's several changes, but each is trivial. 

I've updated the test suite to check for this metadata. Here's the test for this:
```sh
biosimulators-test-suite biosimulators.json \
    -c results_report.SimulatorGeneratesReportsOfSimulationResults
```

### Metadata for SED-ML outputs
- Prepend `sedml` to the names of the attributes which stores SED-ML metadata. This is to clarify how SED-ML metadata is being encoded into HDF5.
   - [ ] `dataSetDataTypes` --> `sedmlDataSetDataTypes`
   - [ ] `dataSetIds` --> `sedmlDataSetIds`
   - [ ] `dataSetLabels` --> `sedmlDataSetLabels`
   - [ ] `dataSetNames` --> `sedmlDataSetNames`
   - [ ] `dataSetShapes` --> `sedmlDataSetShapes`
   - [ ] `id` --> `sedmlId`
- [ ] Change the value of the `_type` attribute from `ODE Data Export` to `Report` (for SED-ML reports), `Plot2D` (for data for SED-ML 2D plots), or `Plot3D` (for data for SED-ML 3D plots)
- [ ] Change the value of the `id` attribute from `report` to the id the SED-ML report/plot (e.g., the values of `sedml:report/@id`, `sedml:plot2d/@id`, `sedml:plot3d/@id`)
- [ ] When SED-ML reports/plots have names, the atttribute `sedmlName` could be added with the value of `sedml:report/@name`, `sedml:plot2d/@name`, or `sedml:plot3d/@name`
- [ ] Add an attribute `uri` with a value equal to the full path to the SED-ML output (e.g., use `experiment-1/simulation-1.sedml/report-1` for a report with id `report-1` in a SED-ML file at `experiment-1/simulation-1.sedml`)

### Metadata for locations in COMBINE archives (HDF5 groups that represent SED-ML files and their parent directories)
- For each HDF5 group add two attributes
   - [ ] `uri`: value equal to the location of the corresponding SED-ML file or parent directory (e.g., `experiment-1/simulation-1.sedml`). This value is also equal to the full path to the HDF5 group.
   - [ ] `combineArchiveLocation`: same value as the `uri` attribute.

**Comment by jonrkarr** [comment]
Thanks for the explanation. Using biosimulators-utils is great; this makes it easier for us to change the data model if needed. 

In that case, the next push of the vcell image should create the additional metadata.

**Comment by gmarupilla** [comment]
No, it is already implemented within the [latest image](https://github.com/orgs/biosimulators/packages/container/package/vcell) and indeed creates all required resultant files. The resultant files for the simulation(UUID [60becbfebe78d19c725d4230](https://run.biosimulations.org/simulations/60becbfebe78d19c725d4230)) have the h5 binary on HPC, but I'm unsure why the status still failed. 

---

@bilalshaikh42, is this because of no `log.yml`?
Additionally, can you verify the resultant files on HPC for 60becbfebe78d19c725d4230?

**Comment by gmarupilla** [comment]
Upon investigating, the latest VCell image uses version [0.1.79](https://pypi.org/project/biosimulators-utils/0.1.79/), but by comparing the [diff-tree](https://github.com/biosimulators/Biosimulators_utils/compare/0.1.79...0.1.81) on GitHub, the functionality achieved from version [0.1.81](https://pypi.org/project/biosimulators-utils/0.1.81/).


For more info, run the below command: 

`docker run -it --entrypoint="/usr/bin/pip3"  ghcr.io/biosimulators/vcell:latest list | grep biosimulators-utils`

**Comment by jonrkarr** [comment]
This is doesn't but not as intended. This is superseded by #81, #82.
