### ISSUE TITLE
Copy Application does not copy diffusion coefficients in initial conditions

### ISSUE THREAD

**Issue by ACowan0105** [virtualcell/vcell#729]
Using the command "Copy Application" Creates a copy of the application with concentrations faithfully copies but all diffusion coefficients are not accurately copied and instead are all set to default values.

**Comment by ACowan0105** [comment]
Also, Microscopy Protocol information also not shared.  Need to check all other application-specific settings and parameters for the copy to be accurate.

**Comment by danv61** [comment]
Which steps were used to reproduce this bug? 
I opened the Tutorial_MultiApp, modified the diffusion coefficients in the 3D pde application, then I right clicked on it and selected Copy. The new application had the correct coefficients.

**Comment by danv61** [comment]
The diffusion coefficients appear to be copied fine, I fixed the Microscope Measurement not being copied

**Comment by danv61** [comment]
Fixed in PR #743
