### ISSUE TITLE
mass action degradation reaction produces incorrect warning

### ISSUE THREAD

**Issue by moraru** [virtualcell/vcell#730]
If a reaction with no product is of type mass action, Kr is (correctly) disabled in the GUI and the math is (correctly) generated as a degradation of the substrate(s).

However, the GUI generates this warning: "Use General Kinetics if you want the reactant to be degraded. As is now this reaction is interpreted as a creation of the reactant".  The warning is both blatantly incorrect and confusing to the user.

**Comment by danv61** [comment]
Fixed in PR #741, commit 9869737
