### ISSUE TITLE
Math compare fails due to inconsistent geometry sizes

### ISSUE THREAD

**Issue by moraru** [virtualcell/vcell#738]
If an application has geometry absolute sizes defined in database vcml which are inconsistent with the geometry relative sizes newly generated math will use the absolute sizes and will be different than legacy math if said legacy math was based on the relative sizes.

Example published biomodel_59361239.

**Comment by moraru** [comment]
If stored math uses relative sizes and absolute sizes are present, the latter need to be checked for accuracy, and if incorrect they should be recomputed on open/import.

**Comment by jcschaff** [comment]
throw away absolute sizes if relative sizes stored and used in math generation.
