### ISSUE TITLE
RuntimeException Error at login

### ISSUE THREAD

**Issue by TemiLeke** [virtualcell/vcell#747]
When I try to log in to VCell v7.4.0, I receive the following error message both on mac and windows systems

_RuntimeException-VCellApiClient communication exception while retrieving server software version: sun.security.validator.ValidatorException: PKIX path validation failed: java.security.cert.CertPathValidatorException: timestamp check failed

SSLHandshakeException-sun.security.validator.ValidatorException: PKIX path validation failed: java.security.cert.CertPathValidatorException: timestamp check failed

ValidatorException-PKIX path validation failed: java.security.cert.CertPathValidatorException: timestamp check failed

CertPathValidatorException-timestamp check failed

CertificateExpiredException-NotAfter: Fri Jan 06 18:59:59 EST 2023_

Is there a fix for this?

**Comment by jcschaff** [comment]
Thanks for opening this issue, we replaced the SSL certificate for VCell API on Monday, Jan 09, 2023.
We have also added SSL cert monitoring which will warn us 30 days in advance of an expiration.
