### ISSUE TITLE
SBML export for parameter overrides

### ISSUE THREAD

**Issue by vcellmike** [virtualcell/vcell#793]
Any published model that has parameters override will give NullPointer Exception
Dreyer 2022, Martin 2021, Rosenbloom 2021
RuntimeException-Could not apply overrides from simulation to application parameters : null
NullPointerException-

King2021 - this model actually has an error in the database
RuntimeException-Unable to perform operation. Errors found:
The Simulation 'Uptake_Larger Jumps' has unused Math Overrides.
 See the Problems panel for a full list of errors and detailed error information.

**Comment by danv61** [comment]
biomodel_225440511
This is the correct message when we export to omex - model has electric
RuntimeException-Error adding model to SEDML document : SimContext 'Application0' could not be exported to SBML :Membrane 'PM has membrane potential enabled, SBML Export is not supported
Exception-SimContext 'Application0' could not be exported to SBML :Membrane 'PM has membrane potential enabled, SBML Export is not supported
UnsupportedSbmlExportException-Membrane 'PM has membrane potential enabled, SBML Export is not supported

**Comment by jcschaff** [comment]
@vcellmike @moraru @danv61 what do we do about exporting applying math overrides in process of SBML export when there are scanned parameters (e.g. skip scanned parameters, fail with message, filter those simulations, or enumerate and choose median values for each).

Any ideas?

**Comment by jcschaff** [comment]
and if there are function dependencies in the parameter, e.g. default = 2.0, actual = (0.06667 * kon), then thinking it would make sense to only apply the numerical values rather than trying to introduce the functional dependency (complex and error prone).

**Comment by jcschaff** [comment]
regarding scanned parameters, will reproduce existing behavior of specifying the job index for each transform and exporting one SBML document per job.
