### ISSUE TITLE
Field data cannot be recovered when rerunning simulations of older models

### ISSUE THREAD

**Issue by ACowan0105** [virtualcell/vcell#806]
If you rerun a saved simulation or copy into a new model/application a simulation that utilizes previously stored filed data, the simulation fails with the following error:

![image](https://user-images.githubusercontent.com/53492064/220370663-d51f3410-7b8d-485e-a3f3-d53671b8346b.png)

If you create new field data, and run a simulation with the new field data, there are no errors.

Note that this will make several published models fail if copied and reused.  It also means Les and I have to rerun a large batch of simulations for a paper we have recently submitted.

**Comment by jcschaff** [comment]
biomodel_252840496.vcml (ACowan - shared with schaff) has broken field data.
