### ISSUE TITLE
BUG: HDF5 files for data for SED-ML reports and plots should be generated consistently

### ISSUE THREAD

**Issue by jonrkarr** [virtualcell/vcell#81]
This the current behavior of VCell
- When SED-ML datasets for the same data generators used in curves are defined, `sedmlDataSetIds` is set equal to the `id`s of the data generators of the curves.
 - [Example](https://github.com/virtualcell/vcell/files/6850355/example.zip)
- When SED-ML datasets for the same data generators used in curves are **NOT** defined, `sedmlDataSetIds` is set equal to the `id`s of the data generators of the curves.
  - [Example](https://github.com/virtualcell/vcell/files/6850349/example.zip)

Instead, this is how data for **plots** should be saved
- [ ] Data for plots should be saved consistently, irrespective of whether SED-ML reports are also defined. Saving data for plots should be independent on any SED-ML reports that are defined.
- [ ] `sedmlDataSetIds` should always be equal to the `id`s of the SED-ML data generators for the curves/surfaces
- [ ] `sedmlDataSetLabels` should be equal to `sedmlDataSetIds`
- [ ] `sedmlDataSetNames` should be equal to the `name`s of the SED-ML data generators for the curves/surfaces

We will temporarily disable VCell for simulation until these are corrected so avoid users encountering errors with plots.

**Comment by jonrkarr** [comment]
I expanded the relevant test case to catch this problem. It can be run as illustrated below:
```
biosimulators-test-suite path/to/biosimulators.json -c sedml.SimulatorProducesLinear2DPlots
```

**Comment by moraru** [comment]
@jonrkarr the example files you provided above are wrong: the sedml output section does not correspond to the expected, this is what is specified in those sedml files, obviously incomplete

  <listOfOutputs>
    <report id="report">
      <listOfDataSets>
        <dataSet id="data_set_time" label="Time (min)" dataReference="data_gen_time"/>
      </listOfDataSets>
    </report>

    <plot2D id="Figure_3a" name="Figure 3a">
      <listOfCurves>
        <curve id="curve_Figure_3a_Sic" xDataReference="data_gen_time" yDataReference="data_gen_Sic"/>
      </listOfCurves>
    </plot2D>
  </listOfOutputs>
</sedML>

**Comment by moraru** [comment]
sorry, the cut and paste above was truncated

 <listOfOutputs>
    <report id="report">
      <listOfDataSets>
        <dataSet id="data_set_time" label="Time (min)" dataReference="data_gen_time"/>
      </listOfDataSets>
    </report>

    <plot2D id="Figure_3a" name="Figure 3a">
      <listOfCurves>
        <curve id="curve_Figure_3a_Sic" xDataReference="data_gen_time" yDataReference="data_gen_Sic"/>
      </listOfCurves>
    </plot2D>
  </listOfOutputs>
</sedML>

**Comment by jonrkarr** [comment]
Ignore the `expectedResults.json`. This only applies to the curated model. When I changed the organization, I forgot to exclude this from the synthetically generated combine archives.

**Comment by jonrkarr** [comment]
The [3 remaining failed test cases](https://github.com/biosimulators/Biosimulators/issues/420#issuecomment-923076539) appear to be due to the same issue, that the data for SED-ML plots is not being exported as expected. Sample results for the Caravagna OMEX file are [here](https://github.com/biosimulators/Biosimulators_test_suite/blob/dev/examples/sbml-core/Caravagna-J-Theor-Biol-2010-tumor-suppressive-oscillations/reports.h5).

**Comment by danv61** [comment]
I really don't know where to look at this point, here are screenshots for the Caravagna omex file, the expected h5 to the left, and the one with my results to the right.
![Caravagna](https://user-images.githubusercontent.com/29076329/134041816-28adb5f5-e588-47c7-8a5a-e380977cb54d.png)

**Comment by jonrkarr** [comment]
Yes, the report looks good. The issue is with the data for plots. The plot data is needed for tools to generate plots outside of SED-ML (e.g., interactive, web-based versions of plots).

**Comment by danv61** [comment]
Here I show side by side the h5 files from the Caravagna omex example - the sample results to the left, the file we produce to the right.
Most of it looks identical, can you please clarify which entries are wrong? 
The biggest difference I can see is with the sedmlDataSetId, but I think we're doing the right thing to concatenate the plot id and the data generator id to obtain unique names. Otherwise, with multiple plots, we may get duplicate data set ids (if we use just the data generator names).

![CaravagnaCompare](https://user-images.githubusercontent.com/29076329/134092942-3854052a-06e0-40be-bc46-bb5b32f43315.png)

**Comment by jonrkarr** [comment]
We're using data generator ids. We're using these ids in the context of plots in SED-ML files at locations in COMBINE archives. Tuples of SED-ML locations, plot ids, and data generator ids are unique. We refer to this as the URI for each data generator. 

I agree with the spirit of your concern that the handling of data for plots isn't ideal. We're hamstrung by the fact that the SED-ML editors have refused to define conventions for outputs and it's difficult to change SED-ML.

**Comment by danv61** [comment]
Fixed.
