### ISSUE TITLE
Fix and upgrade automated restarting of simulation related services

### ISSUE THREAD

**Issue by CodeByDrescher** [virtualcell/vcell#868]
Goal: reduce the frequency of little alerts.

There's got to be a reason for outages of a few minutes

**Comment by CodeByDrescher** [comment]
It'd be nice if the user got some sort of notification of what's happening and how they should proceed.

**Comment by jcschaff** [comment]
after switch to Kubernetes, which has better tracking of memory usage, and after disabling expensive blocking API endpoints for OMEX generation, VCell Simulation-related services are now more stable and automatically restarted upon excessive memory usage.
