### ISSUE TITLE
Hanging up on "Waiting to dispatch"

### ISSUE THREAD

**Issue by lesloew** [virtualcell/vcell#873]
The following has been happening consistently over the last several days on Windows (probably also on Mac). After a VCell BioModel has been open for some time and I try to run a sim, the system hangs up on "Waiting to Dispatch". Reconnect just gives a spinning circle (on Windows). I have to force quit (end task) VCell. When I start up again, the sims are running fine (I can also start up VCell on a different machine and see that they are running fine even before force quitting). This only happens when I try to run a sim; saving changes to the BioModel (e.g. annotations) works fine and retrieving sim results works fine.

**Comment by ACowan0105** [comment]
A miracle seems to have happened......Currently does not seem to be an issue
