### ISSUE TITLE
reenable web app authentication via cookies 

### ISSUE THREAD

**Issue by jcschaff** [virtualcell/vcell#905]
VCell has some browser-based functionality which uses cookies and template driven web content with login forms (e.g. when invoking https://vcellapi.cam.uchc.edu/biomodel from a browser which accepts HTML rather than an API client which expects JSON).

The browser-based auth relied on Cookies and a login form.  During the previous Authentication upgrade, such Cookie based auth was temporarily removed to be reimplemented as needed (or replaced entirely when the API technology is upgraded).

By popular demand, we need to restore the form/cookie based authentication for administrative and browser-preview webapps.

**Comment by jcschaff** [comment]
after test deploy with remote debugging, need to separate cookie verification from bearer token verification.

**Comment by ACowan0105** [comment]
update forms for publications to make operational, make stats page available

For publications: https://vcell-node4:8080/biomodel

For stats: http://code3.cam.uchc.edu/statistics.php (old)

replaced by https://vcellapi-beta.cam.uchc.edu:8080/rpc?stats

**Comment by CodeByDrescher** [comment]
closed, see #936 for continuation.
