### ISSUE TITLE
Curator access to database needs fixes, specifically to flags

### ISSUE THREAD

**Issue by CodeByDrescher** [virtualcell/vcell#936]
update forms for publications to make operational, make stats page available

For publications: https://vcell-node4:8080/biomodel

For stats: http://code3.cam.uchc.edu/statistics.php (old)

replaced by https://vcellapi-beta.cam.uchc.edu:8080/rpc?stats

**Comment by jcschaff** [comment]
Fixed - see new URLs.

For publications, see: https://vcellapi.cam.uchc.edu/publication
For stats, see:  https://vcellapi.cam.uchc.edu/admin/stats
