### ISSUE TITLE
Faithfully process names for SED-ML outputs (avoid inventing names for SED-ML elements when names aren't set)

### ISSUE THREAD

**Issue by jonrkarr** [virtualcell/vcell#94]
The hidden screenshot at https://github.com/virtualcell/vcell/issues/81#issuecomment-923100525 shows a `sedmlName` attribute. However, the `name` for this SED-ML report is not set. Only the `id` attribute for this report is set.

It looks like VCell is creating names when names aren't set. When names aren't set, VCell appears to be setting names equal to ids. This conflates the separate purposes of ids and names.

If the name isn't set, it should ideally stay this way (i.e., `null`/`None`), at least when outputs are generated, such as at [`vcell-cli-utils/vcell_cli_utils/cli.py#L55`](https://github.com/virtualcell/vcell/blob/a9fa4a014601586e94bbbda6beb3a95327621f81/vcell-cli-utils/vcell_cli_utils/cli.py#L55).

**Comment by jonrkarr** [comment]
I think this has been resolved

**Comment by moraru** [comment]
Fixed
