### ISSUE TITLE
SBML export for models with rule-based features

### ISSUE THREAD

**Issue by vcellmike** [virtualcell/vcell#964]
VCell models that are simple reaction networks but have molecules (no reaction rules) can not be exported to SBML. Should be able to be exported, eliminating molecules (or keeping BNGL specs somewhere in annotations).

**Comment by danv61** [comment]
Fixed in commit 4eda506
We now allow exporting for flattened reaction networks (rule based but no rules)

**Comment by danv61** [comment]
PR #965
