### ISSUE TITLE
NFSim export gives an error when exporting a model expanded from rules

### ISSUE THREAD

**Issue by vcellmike** [virtualcell/vcell#974]
Two emails from vcellserver 9:55am and 10:07am are about this issue, ending in 

java.lang.Thread.run(Thread.java:748)\njava.lang.ArrayIndexOutOfBoundsException: 0\n\tat cbit.vcell.mapping.SimulationContext.getSimulations(SimulationContext.java:1777)\n\tat org.vcell.util.gui.exporter.NfsimExtensionFilter.writeBioModel(NfsimExtensionFilter.java:35)\n\tat cbit.vcell.client.task.ExportDocument.run(ExportDocument.java:134)\n\tat cbit.vcell.client.task.ClientTaskDispatcher.runTask(ClientTaskDispatcher.java:675)\n\tat cbit.vcell.client.task.ClientTaskDispatcher.access$600(ClientTaskDispatcher.java:55)\n\tat cbit.vcell.client.task.ClientTaskDispatcher$1.construct(ClientTaskDispatcher.java:382)\n\tat swingthreads.SwingWorker$2.run(SwingWorker.java:109)\n\tat java.lang.Thread.run(Thread.java:748)\n","softwareVersion":"Rel_Version_7.5.0_build_62","platform":"Running under Java 1.8.0_141, published by Oracle Corporation, on the x86_64 architecture running version 10.16 of the Mac OS X operating system"}

**Comment by danv61** [comment]
Indirectly fixed apparently
